pr:
- main

stages:
  - stage: build_publish_image_stage
    displayName: Build and Publish Image
    jobs:
      - deployment: build_publish_image_deployment
        displayName: Build and Publish Image Deployment
        environment: AWS-Reference-Container-Registry
        pool:
          vmImage: ubuntu-latest

        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AWSCLI@1
                  inputs:
                    awsCredentials: ECRServiceConnection
                    regionName: ap-southeast-2
                    awsCommand: ecr
                    awsSubCommand: get-login-password
                    awsArguments: '| docker login --username AWS --password-stdin 282907128248.dkr.ecr.ap-southeast-2.amazonaws.com' 

                - task: DockerCompose@0
                  displayName: Build Service
                  inputs:
                    action: Build Services
                    dockerComposeFile: Applications/docker-compose.yml
                    dockerComposeFileArgs: |
                      DOCKER_REGISTRY=282907128248.dkr.ecr.ap-southeast-2.amazonaws.com/

                - task: DockerCompose@0
                  displayName: Push services
                  inputs:
                    action: Push services
                    dockerComposeFile: Applications/docker-compose.yml
                    dockerComposeFileArgs: |
                      DOCKER_REGISTRY=282907128248.dkr.ecr.ap-southeast-2.amazonaws.com/                     