pr:
- main

stages:
  - stage: build_publish_image_stage
    displayName: Build and Publish Image
    jobs:
      - deployment: build_publish_image_deployment
        displayName: Build and Publish Image Deployment
        environment: AWS-Reference-Container-Registry
        pool:
          vmImage: ubuntu-latest

        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                
                - task: AWSShellScript@1
                  displayName: Login to Docker
                  inputs:
                    awsCredentials: ECRServiceConnection
                    regionName: ap-southeast-2
                    scriptType: inline
                    inlineScript: 'aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 282907128248.dkr.ecr.ap-southeast-2.amazonaws.com'

                - task: DockerCompose@0
                  displayName: Build Service
                  inputs:
                    action: Build Services
                    dockerComposeFile: Applications/docker-compose.yml
                    dockerComposeFileArgs: |
                      DOCKER_REGISTRY=282907128248.dkr.ecr.ap-southeast-2.amazonaws.com/

                - task: DockerCompose@0
                  displayName: Push services
                  inputs:
                    action: Push services
                    dockerComposeFile: Applications/docker-compose.yml
                    dockerComposeFileArgs: |
                      DOCKER_REGISTRY=282907128248.dkr.ecr.ap-southeast-2.amazonaws.com/                     